name: Production Deployment Pipeline to Hugging Face Spaces

on:
  push:
    branches: [ master ]  # Triggers automatically when you push to master

jobs:
  deploy-to-space:
    runs-on: ubuntu-latest
    steps:
      - name: Ingest Source Code Repository Files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mount Production Git Synchronizer Configurations
        env:
          HF_TOKEN: ${{ secrets.HF_SPACE_DEPLOY_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Automated-GitHub-Actions-Runner"
          
          # Links your workflow runner directly to your live Hugging Face Space
          git remote add space https://huggingface.co/spaces/Armaghan6623/customer-churn-mlops
          
          # Pushes the 'customer_churn_saas' subfolder directly as the root of your Hugging Face Space
          git subtree push --prefix customer_churn_saas space main